use_frameworks!

platform :ios, '15.0'

target 'nRF-Wi-Fi-Provisioner (iOS)' do
  pod 'NordicWiFiProvisioner-BLE', :path => '../'
  pod 'NordicWiFiProvisioner-SoftAP', :path => '../'

  target 'Tests iOS' do
    inherit! :search_paths
  end
end
