# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
    # "iPad Air (5th generation)",
    # "iPad Pro (12.9-inch) (6th generation)",
    # "iPad Pro (12.9-inch) (2nd generation)",
    # "iPad mini (6th generation)",
    # "iPhone 8 Plus",
    # "iPhone 13 mini",
    "iPhone 14",
    # "iPhone 14 Plus",
    # "iPhone 14 Pro",
    # "iPhone SE (3rd generation)"
])

# languages([
#   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
# ])

# The name of the scheme which contains the UI Tests
scheme("Tests iOS")

workspace("nRF-Wi-Fi-Provisioner.xcworkspace")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments([
#     # "-AppleInterfaceStyle Dark",
#     "-AppleInterfaceStyle Light"
# ])

concurrent_simulators(true)

# For more information about all available options run
# fastlane action snapshot

erase_simulator(true)

