// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum Band: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case unspecified // = 0
  case band24Ghz // = 1
  case band5Ghz // = 2
  case band6Ghz // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .band24Ghz
    case 2: self = .band5Ghz
    case 3: self = .band6Ghz
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .band24Ghz: return 1
    case .band5Ghz: return 2
    case .band6Ghz: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Band: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Band] = [
    .unspecified,
    .band24Ghz,
    .band5Ghz,
    .band6Ghz,
  ]
}

#endif  // swift(>=4.2)

enum AuthMode: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case unspecified // = 0
  case `open` // = 1
  case wep // = 2
  case wpaPsk // = 3
  case wpa2Psk // = 4
  case wpaWpa2Psk // = 5
  case wpa2Enterprise // = 6
  case wpa3Psk // = 7
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .open
    case 2: self = .wep
    case 3: self = .wpaPsk
    case 4: self = .wpa2Psk
    case 5: self = .wpaWpa2Psk
    case 6: self = .wpa2Enterprise
    case 7: self = .wpa3Psk
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .open: return 1
    case .wep: return 2
    case .wpaPsk: return 3
    case .wpa2Psk: return 4
    case .wpaWpa2Psk: return 5
    case .wpa2Enterprise: return 6
    case .wpa3Psk: return 7
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension AuthMode: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [AuthMode] = [
    .unspecified,
    .open,
    .wep,
    .wpaPsk,
    .wpa2Psk,
    .wpaWpa2Psk,
    .wpa2Enterprise,
    .wpa3Psk,
  ]
}

#endif  // swift(>=4.2)

struct WifiScanResult {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var ssid: String = String()

  var bssid: String = String()

  var band: Band = .unspecified

  var channel: UInt32 = 0

  var authMode: AuthMode = .unspecified

  var rssi: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct ScanResults {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var results: [WifiScanResult] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct WifiConfig {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var ssid: String = String()

  var passphrase: String = String()

  var band: Band = .unspecified

  var channel: UInt32 = 0

  var authMode: AuthMode = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Band: @unchecked Sendable {}
extension AuthMode: @unchecked Sendable {}
extension WifiScanResult: @unchecked Sendable {}
extension ScanResults: @unchecked Sendable {}
extension WifiConfig: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Band: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "BAND_UNSPECIFIED"),
    1: .same(proto: "BAND_2_4_GHZ"),
    2: .same(proto: "BAND_5_GHZ"),
    3: .same(proto: "BAND_6_GHZ"),
  ]
}

extension AuthMode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "AUTH_MODE_UNSPECIFIED"),
    1: .same(proto: "OPEN"),
    2: .same(proto: "WEP"),
    3: .same(proto: "WPA_PSK"),
    4: .same(proto: "WPA2_PSK"),
    5: .same(proto: "WPA_WPA2_PSK"),
    6: .same(proto: "WPA2_ENTERPRISE"),
    7: .same(proto: "WPA3_PSK"),
  ]
}

extension WifiScanResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "WifiScanResult"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "ssid"),
    2: .same(proto: "bssid"),
    3: .same(proto: "band"),
    4: .same(proto: "channel"),
    5: .same(proto: "authMode"),
    6: .same(proto: "rssi"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.ssid) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.bssid) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.band) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.channel) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.authMode) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.rssi) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.ssid.isEmpty {
      try visitor.visitSingularStringField(value: self.ssid, fieldNumber: 1)
    }
    if !self.bssid.isEmpty {
      try visitor.visitSingularStringField(value: self.bssid, fieldNumber: 2)
    }
    if self.band != .unspecified {
      try visitor.visitSingularEnumField(value: self.band, fieldNumber: 3)
    }
    if self.channel != 0 {
      try visitor.visitSingularUInt32Field(value: self.channel, fieldNumber: 4)
    }
    if self.authMode != .unspecified {
      try visitor.visitSingularEnumField(value: self.authMode, fieldNumber: 5)
    }
    if self.rssi != 0 {
      try visitor.visitSingularInt32Field(value: self.rssi, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: WifiScanResult, rhs: WifiScanResult) -> Bool {
    if lhs.ssid != rhs.ssid {return false}
    if lhs.bssid != rhs.bssid {return false}
    if lhs.band != rhs.band {return false}
    if lhs.channel != rhs.channel {return false}
    if lhs.authMode != rhs.authMode {return false}
    if lhs.rssi != rhs.rssi {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ScanResults: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ScanResults"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "results"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.results) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.results.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.results, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ScanResults, rhs: ScanResults) -> Bool {
    if lhs.results != rhs.results {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension WifiConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "WifiConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "ssid"),
    2: .same(proto: "passphrase"),
    3: .same(proto: "band"),
    4: .same(proto: "channel"),
    5: .same(proto: "authMode"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.ssid) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.passphrase) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.band) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.channel) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.authMode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.ssid.isEmpty {
      try visitor.visitSingularStringField(value: self.ssid, fieldNumber: 1)
    }
    if !self.passphrase.isEmpty {
      try visitor.visitSingularStringField(value: self.passphrase, fieldNumber: 2)
    }
    if self.band != .unspecified {
      try visitor.visitSingularEnumField(value: self.band, fieldNumber: 3)
    }
    if self.channel != 0 {
      try visitor.visitSingularUInt32Field(value: self.channel, fieldNumber: 4)
    }
    if self.authMode != .unspecified {
      try visitor.visitSingularEnumField(value: self.authMode, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: WifiConfig, rhs: WifiConfig) -> Bool {
    if lhs.ssid != rhs.ssid {return false}
    if lhs.passphrase != rhs.passphrase {return false}
    if lhs.band != rhs.band {return false}
    if lhs.channel != rhs.channel {return false}
    if lhs.authMode != rhs.authMode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
